[book]
authors = ["MJ PC Lab"]
language = "zh-CN"
title = "学习curl"

[build]
build-dir = "dist"

[output.html]
git-repository-url = "https://github.com/mjpclab/learning-curl"
print.enable = false
playground.copyable = false
preferred-dark-theme = "ayu"
